# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: ' $(docker.id)/aramladder:$(build.buildId)'

steps:
- script: docker login -u $(docker.id) -p '$(docker.password)'
- script: docker build -f ARAMLadder/Dockerfile -t $(imageName) .
  displayName: 'docker build'
  
- script: docker push $(imageName)
  displayName: 'docker push'
  
  
  
